apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: back-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: back-app
  template:
    metadata:
      labels:
        app: back-app
    spec:
      containers:
      - name: backend
        image: salmahesham1114/devops-test-project:backend
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
